# Generated by Django 3.0.8 on 2020-07-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200723_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_for_date',
            new_name='for_date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reported_on_datetime',
            new_name='on_datetime',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reported_student_count',
            new_name='student_count',
        ),
        migrations.AddField(
            model_name='report',
            name='added_by_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('school', 'for_date', 'added_by_school')},
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Report')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='estimated_menu',
        ),
        migrations.RemoveField(
            model_name='report',
            name='estimated_student_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_menu',
        ),
    ]
