# Generated by Django 3.0.8 on 2020-07-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200728_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='actual_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_report', to='api.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('school', 'for_date', 'actual_report')},
        ),
        migrations.AlterUniqueTogether(
            name='reportitem',
            unique_together={('report', 'item')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='added_by_school',
        ),
    ]
