# Generated by Django 3.0.8 on 2020-07-18 07:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200717_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporter',
            new_name='School',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_student_count', models.PositiveIntegerField()),
                ('reported_menu', django.contrib.postgres.fields.jsonb.JSONField()),
                ('reported_for_date', models.DateField(verbose_name='date reported for')),
                ('reported_on_datetime', models.DateTimeField(default=django.db.models.functions.datetime.Now(), verbose_name='date and time reported on')),
                ('estimated_student_count', models.PositiveIntegerField()),
                ('estimated_menu', django.contrib.postgres.fields.jsonb.JSONField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School', unique_for_date='reported_for_date')),
            ],
        ),
    ]
