# Generated by Django 3.0.8 on 2020-07-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200718_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='school',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Authority'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.District'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.District'),
        ),
    ]
