# Generated by Django 3.0.8 on 2020-08-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200801_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('item', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.District')),
            ],
            options={
                'unique_together': {('district', 'day')},
            },
        ),
    ]
