# Generated by Django 3.0.8 on 2020-08-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200802_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='api.Report')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='api.Report')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
            options={
                'unique_together': {('school', 'for_date')},
            },
        ),
    ]
